name: Rust - Tests

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  aoc2025:
    name: "Advent of Code 2025"
    runs-on: ubuntu-latest-prettysunflower
    strategy:
      matrix:
        toolchain:
          - stable
    defaults:
      run:
        working-directory: ./2025/rust
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --workspace --verbose
      - run: cargo test --workspace --verbose
